apiVersion: batch/v1
kind: Job
metadata:
  name: "run-slab-rx"
  namespace: brook-wander
spec:
  completions: 22
  parallelism: 22
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
#       backoffLimitPerIndex: 2
#       maxFailedIndexes: 900
      containers:
      - env:
        command:
        - /bin/bash
        - -c
        args:
        - echo ${JOB_COMPLETION_INDEX} && JOB_ID=$((${JOB_COMPLETION_INDEX}+0)) && cd /home/jovyan/shared-scratch/Brook/gibbs_proj/cpes/slab_vasp_relaxations/$JOB_ID/ && mpirun -np 16 --map-by hwthread /opt/vasp.6.1.2_pgi_mkl_beef/bin/vasp_std
        image: 'ulissigroup/kubeflow_vasp:extras-notebook'
        name: 'sample-load'
        resources:
          limits:
            cpu: 16
            memory: 16Gi
          requests:
            cpu: 16
            memory: 16Gi
        volumeMounts:
        - mountPath: /home/jovyan/shared-scratch/
          name: shared-scratch
        - mountPath: /home/jovyan/
          name: workspace-inference
      volumes:
      - name: shared-scratch
        persistentVolumeClaim:
          claimName: shared-scratch
      - name: workspace-inference
        persistentVolumeClaim:
          claimName: workspace-inference
      priorityClassName: default-priority
